q-- 1. Vehicles Table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
    fuel_type TEXT NOT NULL,
    seating_capacity INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Rentals / Bookings Table
CREATE TABLE IF NOT EXISTS rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- references Supabase auth.users
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_cost NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- Sample Data (3 vehicles for testing)
INSERT INTO vehicles (brand, model, year, category, daily_rate, fuel_type, seating_capacity, status)
VALUES
    ('Tesla', 'Model 3', 2024, 'Electric', 4500.00, 'EV', 5, 'available'),
    ('Toyota', 'Fortuner', 2023, 'SUV', 3500.00, 'Diesel', 7, 'available'),
    ('Honda', 'City', 2023, 'Sedan', 2200.00, 'Petrol', 5, 'available');
